create table if not exists public.users (
    user_id bigint generated by default as identity primary key,
    name text not null,
    role text not null check (role in ('caregiver', 'senior')),
    caregiver_id bigint references public.users(user_id),
    baseline_avg_tx numeric not null default 5000
);

create table if not exists public.transactions (
    tx_id bigint generated by default as identity primary key,
    sender_id bigint not null references public.users(user_id),
    payee_name text not null,
    payee_account text not null,
    amount numeric not null check (amount > 0),
    note text not null default '',
    risk_score integer,
    risk_reasons text not null default '',
    status text not null,
    resolution text,
    cooling_off_expiry timestamptz,
    created_at timestamptz not null default now()
);

create index if not exists transactions_sender_created_idx
    on public.transactions (sender_id, created_at desc);

create index if not exists transactions_status_created_idx
    on public.transactions (status, created_at desc);

insert into public.users (user_id, name, role, caregiver_id, baseline_avg_tx)
values
    (1, 'Priya (Caregiver)', 'caregiver', null, 0),
    (2, 'Meena Sharma', 'senior', 1, 2000),
    (101, 'Ramesh (Senior)', 'senior', 201, 2000),
    (201, 'Priya (Caregiver)', 'caregiver', null, 0)
on conflict (user_id) do nothing;